In [9]:
import torch.nn.functional as F
import torch 

a = torch.linspace(3, 7, 10)
F.pad(a, [1, 0], value=1)

tensor([1.0000, 3.0000, 3.4444, 3.8889, 4.3333, 4.7778, 5.2222, 5.6667, 6.1111,
        6.5556, 7.0000])

In [15]:
t4d = torch.empty(3, 3, 4, 2)
p1d = (2, 2) # pad last dim by 1 on each side
out = F.pad(t4d, p1d, "constant", 10)  # effectively zero padding

In [16]:
out.shape

torch.Size([3, 3, 4, 6])

In [8]:
import logging

level = getattr(logging, "INFO", None)
level

20

In [9]:
a = 'abc.nii.gz'
a[:-7]

'abc'

In [11]:
import numpy as np
import torch
a = torch.zeros((3, 3, 4)).unsqueeze(0)

In [12]:
a.shape

torch.Size([1, 3, 3, 4])

In [26]:
class A:
    def __init__(self):
        self.a = 1
        self.b = 2

    @staticmethod
    def add(x, y):
        return x + y
class B(A):
    def __init__(self):
        super().__init__()
        self.c = 3

    def printing(self):
        print(self.a, self.b, self.c)
        print(self.add(1, 2))

b = B()
b.printing()

1 2 3
3


In [22]:
np.asarray(list(range(0, 10, 2))) + 1

array([1, 3, 5, 7, 9])

In [6]:
import torch
import torchvision
from torchvision import transforms
import torchvision.datasets as datasets
from torch.utils.data import Dataset, DataLoader

trans = transforms.Compose([
                                        transforms.RandomHorizontalFlip(),
                                        transforms.ToTensor(),
                                        # transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                                ])

cifar_trainset = datasets.CIFAR10(root='./data', train=True, download=True, transform=trans)

dl = DataLoader(cifar_trainset, batch_size=10, shuffle=True, num_workers=0, drop_last=True)

def cycle(dataloader):
    while True:
        for x, y in iter(dataloader):
            yield x, y

loop = cycle(dl)
images, label = next(loop)
label

Files already downloaded and verified


tensor([0, 7, 9, 6, 4, 1, 3, 1, 4, 2])

tensor(0.)

In [1]:
import torch

lab = torch.ones(5, dtype=torch.long) * \
        torch.arange(start = 0, end = 10).reshape(-1, 1)

In [7]:
lab.reshape(-1,1).squeeze()

tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4,
        4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9,
        9, 9])